### ISSUE TITLE
commit时，报模块找不到

### ISSUE THREAD

**Issue by robinma** [jd-antelope/s-lint#6]
commit测试，提出错误

`
husky > commit-msg (node v14.15.4)
/lintdemo/node_modules/@commitlint/cli/lib/cli.js:112
        throw err;
        ^

Error: Cannot find module "conventional-changelog-lint-config-commitlint-config-selling" from "/.../git/lintdemo"
`

**Comment by robinma** [comment]
多次测试有此问题

**Comment by zxyue25** [comment]
我也发现了，正在排查中哈

**Comment by robinma** [comment]
查看commitlint源代码。extends后面写上模块绝对地址，可正常执行

**Comment by robinma** [comment]
https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/resolve-extends/src/index.ts#L81

**Comment by huozhongyi123** [comment]
已修复，看最新文档吧
